{
  "DB_NAME":"",
  "DB_USER":"",
  "DB_PASSWORD":"",
  "DB_HOST":"",
  "DB_CHARSET":"",
  "DB_COLLATE":"",
  "WP_CONTENT_DIR":"",
  "AUTH_KEY":"",
  "SECURE_AUTH_KEY":"",
  "LOGGED_IN_KEY":"",
  "NONCE_KEY":"",
  "AUTH_SALT":"",
  "SECURE_AUTH_SALT":"",
  "LOGGED_IN_SALT":"",
  "NONCE_SALT":""
}